Repository Kodeworks/liquidator, pull requests merged in 2019-09, with the labels that each got.

#152 Also fetch all recurring transactions on load
  frontend/package.json
  frontend/src/store/contexts/transactions.tsx
Labels: bug

#153 Fetch new user when creating company so it picks up the new company
  frontend/src/components/pages/Companies.tsx
Labels: feature

#169 Update error scheme to match backend, and prevent login loop
  frontend/src/components/atoms/Routes.tsx
  frontend/src/components/molecules/AddTransaction.tsx
  frontend/src/mitochondria/index.ts
Labels: improvement

#160 Dashboard and various improvements
  frontend/package.json
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/atoms/CompanyUser.tsx
  frontend/src/components/atoms/CurrentBalanceEntry.tsx
  frontend/src/components/atoms/Routes.tsx
  frontend/src/components/atoms/Select.tsx
  frontend/src/components/atoms/TransactionEntry.tsx
  frontend/src/components/atoms/UpdateCompanyForm.tsx
  frontend/src/components/molecules/Chart.tsx
  frontend/src/components/molecules/Company.tsx
  frontend/src/components/molecules/CurrentBalance.tsx
  frontend/src/components/molecules/IncomeTransactions.tsx
  frontend/src/components/molecules/TransactionCalculator.tsx
  frontend/src/components/organism/Navigation.tsx
  frontend/src/components/organism/Projections.tsx
  frontend/src/components/organism/Toolbar.tsx
  frontend/src/components/organism/Transactions.tsx
  frontend/src/components/pages/Balances.tsx
  frontend/src/components/pages/Companies.tsx
  frontend/src/components/pages/Dashboard.tsx
  frontend/src/helpers/explode_recurring.tsx
  frontend/src/store/reducers/__tests__/auth.test.ts
  frontend/src/store/reducers/auth.ts
  frontend/src/styling/global.ts
  frontend/yarn.lock
Labels: bug, feature, improvement, priority

#171 Remove initial state for amount in AddTransaction.tsx so that placeho…
  frontend/src/components/molecules/AddTransaction.tsx
Labels: improvement
