Repository Kodeworks/liquidator, pull requests merged in 2019-07, with the labels that each got.

#51 Feature/auth
  package.json
  src/App.tsx
  src/components/atoms/CardContainer.tsx
  src/components/atoms/Collapsable.tsx
  src/components/atoms/Input.tsx
  src/components/organism/Authentication/Authentication.tsx
  src/components/organism/Authentication/Login.tsx
  src/components/organism/Authentication/Register.tsx
  src/components/organism/AuthenticationCard.tsx
  src/components/organism/Toolbar.tsx
  src/components/organism/__test__/Authentication.test.tsx
  src/contexts/auth.ts
  src/contexts/transaction.ts
  src/declarations/auth.ts
  src/declarations/user.ts
  src/helpers/GlobalWrapper.tsx
  src/helpers/intermediary_calc.ts
  src/helpers/test-utils.ts
  src/mitochondria/auth.ts
  src/reducers/auth.ts
  src/reducers/transactions.ts
  src/stories/Authentication.stories.tsx
  src/stories/index.stories.tsx
  src/styling/global.ts
  tslint.json
  yarn.lock
Labels: enhancement

#56 Feature/balances
  package.json
  robohydra/balances.conf
  robohydra/plugins/balancesplugin/index.js
  robohydra/plugins/balancesplugin/months.js
  src/App.tsx
  src/components/atoms/BalanceTableEntry.tsx
  src/components/atoms/MonthPicker.tsx
  src/components/atoms/PageTitle.tsx
  src/components/atoms/__tests__/BalanceTableEntry.test.tsx
  src/components/atoms/__tests__/MonthPicker.test.tsx
  src/components/molecules/BalancesTable.tsx
  src/components/molecules/__tests__/BalancesTable.test.tsx
  src/components/organism/Balances.tsx
  src/components/organism/Navigation.tsx
  src/declarations/balanceEntries.ts
  src/declarations/month.ts
  src/helpers/__tests__/currency.test.ts
  src/helpers/currency.ts
  src/mitochondria/balances.ts
  src/stories/BalancesList.stories.tsx
  src/styling/global.ts
  yarn.lock
Labels: documentation, enhancement

#64 Hotfix/transaction type
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/TransactionEntry.test.tsx
  src/components/molecules/ExpenseTransactions.tsx
  src/components/molecules/IncomeTransactions.tsx
  src/components/molecules/__tests__/Filters.test.tsx
  src/components/organism/Balances.tsx
  src/declarations/month.ts
  src/declarations/transaction.ts
  src/helpers/intermediary_calc.ts
  src/helpers/transaction_creator.ts
  src/reducers/__tests__/transactions.test.ts
Labels: improvement

#65 Create db.json with fake data
  db.json
Labels: documentation

#75 Await Perform.doSetUser to fix refresh token expiry
  src/App.tsx
  src/mitochondria/auth.ts
Labels: bug

#79 Feature/generalize fetching
  src/mitochondria/__test__/api.test.ts
  src/mitochondria/auth.ts
  src/mitochondria/index.ts
  src/mitochondria/transactions.ts
  src/store/reducers/auth.ts
  src/store/reducers/transactions.ts
Labels: improvement

#63 AddTransaction component has functionality to update state and backend API
  .gitignore
  .json-server/db.json
  .json-server/generator.txt
  .json-server/server.js
  .vscode/settings.json
  db.json
  package.json
  src/App.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/TransactionEntry.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/ExpenseTransactions.tsx
  src/components/molecules/Filters.tsx
  src/components/molecules/IncomeTransactions.tsx
  src/components/molecules/TransactionCalculator.tsx
  src/components/molecules/__tests__/AddTransaction.test.tsx
  src/components/molecules/__tests__/BalancesTable.test.tsx
  src/components/molecules/__tests__/Filters.test.tsx
  src/components/organism/Authentication/Login.tsx
  src/components/organism/Authentication/Register.tsx
  src/components/organism/Toolbar.tsx
  src/components/organism/Transactions.tsx
  src/components/pages/Homepage.tsx
  src/contexts/transaction.ts
  src/declarations/month.ts
  src/declarations/transaction.ts
  src/helpers/GlobalWrapper.tsx
  src/helpers/__tests__/transaction_creator.test.ts
  src/helpers/intermediary_calc.ts
  src/helpers/transaction_creator.ts
  src/helpers/transaction_creator.tsx
  src/mitochondria/__test__/api.test.ts
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/index.ts
  src/mitochondria/transactions.ts
  src/reducers/__tests__/transactions.test.ts
  src/reducers/transactions.ts
  src/store/contexts/auth.ts
  src/store/contexts/transactions.tsx
  src/store/reducers/__tests__/transactions.test.ts
  src/store/reducers/auth.ts
  src/store/reducers/transactions.ts
  yarn.lock
Labels: feature

#78 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#71 Feature/balances calendar
  src/components/atoms/BalanceTableEntry.tsx
  src/components/atoms/BalancesCalendarEntry.tsx
  src/components/atoms/BalancesViewPicker.tsx
  src/components/atoms/MonthPicker.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/BalanceTableEntry.test.tsx
  src/components/atoms/__tests__/BalancesCalendarEntry.test.tsx
  src/components/atoms/__tests__/BalancesViewPicker.test.tsx
  src/components/atoms/__tests__/MonthPicker.test.tsx
  src/components/molecules/BalancesCalendar.tsx
  src/components/molecules/BalancesTable.tsx
  src/components/molecules/__tests__/BalancesCalendar.test.tsx
  src/components/molecules/__tests__/BalancesTable.test.tsx
  src/components/organism/Balances.tsx
  src/helpers/__tests__/currency.test.ts
  src/mitochondria/auth.ts
  src/stories/Balances.stories.tsx
  src/stories/BalancesList.stories.tsx
  src/stories/index.stories.tsx
Labels: feature

#82 Make balances.ts::getMonth use new fetch pattern
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/transactions.ts
Labels: improvement

#89 Hotfix/register redirect
  src/App.tsx
  src/components/organism/__test__/Authentication.test.tsx
  src/components/organism/authentication/Authentication.tsx
  src/components/organism/authentication/Login.tsx
  src/components/organism/authentication/Register.tsx
  src/store/reducers/auth.ts
  src/stories/Authentication.stories.tsx
Labels: bug, improvement

#85 Feature/test auth
  robohydra/plugins/balancesplugin/index.js
  src/components/pages/Balances.tsx
  src/mitochondria/__test__/api.test.ts
  src/mitochondria/__test__/auth.test.ts
  src/mitochondria/__test__/transaction.test.ts
  src/mitochondria/balances.ts
  src/mitochondria/index.ts
Labels: feature

#90 Feature/company
  src/App.test.tsx
  src/App.tsx
  src/components/atoms/AccentedLink.tsx
  src/components/atoms/Routes.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/__tests__/AddTransaction.test.tsx
  src/components/molecules/__tests__/Filters.test.tsx
  src/components/organism/Navigation.tsx
  src/components/organism/Toolbar.tsx
  src/components/organism/authentication/Authentication.tsx
  src/components/organism/authentication/Login.tsx
  src/components/organism/authentication/Register.tsx
  src/components/pages/Companies.tsx
  src/declarations/auth.ts
  src/declarations/company.ts
  src/declarations/month.ts
  src/declarations/pagination.ts
  src/declarations/user.ts
  src/helpers/GlobalWrapper.tsx
  src/helpers/transaction_creator.tsx
  src/mitochondria/__test__/auth.test.ts
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/store/contexts/auth.ts
  src/store/contexts/auth.tsx
  src/store/contexts/company.tsx
  src/store/reducers/__tests__/transactions.test.ts
  src/store/reducers/auth.ts
  src/store/reducers/company.ts
  src/store/reducers/transactions.ts
Labels: feature

#95 Remove unnecessary variable from store/**/company.ts
  src/store/contexts/company.tsx
  src/store/reducers/company.ts
Labels: improvement

#103 Add test commands to README.md
  README.md
Labels: documentation

#106 Feature/dashboard tabs
  src/components/atoms/Routes.tsx
  src/components/atoms/TabLabel.tsx
  src/components/molecules/Tab.tsx
  src/components/molecules/TabMenu.tsx
  src/components/molecules/TabsContainer.tsx
  src/components/molecules/__tests__/TabsContainer.test.tsx
  src/components/pages/Dashboard.tsx
  src/stories/index.stories.tsx
Labels: feature

#101 Feature/api
  .json-server/db.json
  .json-server/generator.txt
  .json-server/server.js
  README.md
  package.json
  robohydra/plugins/balancesplugin/months.js
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/TransactionEntry.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/ExpenseTransactions.tsx
  src/components/molecules/Filters.tsx
  src/components/molecules/IncomeTransactions.tsx
  src/components/molecules/__tests__/Filters.test.tsx
  src/components/organism/Toolbar.tsx
  src/components/organism/authentication/Login.tsx
  src/components/pages/Balances.tsx
  src/declarations/balance.ts
  src/declarations/month.ts
  src/declarations/pagination.ts
  src/declarations/transaction.ts
  src/helpers/intermediary_calc.ts
  src/helpers/test-utils.ts
  src/helpers/transaction_creator.tsx
  src/mitochondria/__test__/auth.test.ts
  src/mitochondria/__test__/auth.ts
  src/mitochondria/__test__/balances.ts
  src/mitochondria/__test__/company.ts
  src/mitochondria/__test__/run.test.ts
  src/mitochondria/__test__/transaction.test.ts
  src/mitochondria/__test__/transaction.ts
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/mitochondria/recurring.ts
  src/mitochondria/transactions.ts
  src/store/reducers/auth.ts
  src/store/reducers/transactions.ts
  src/stories/index.stories.tsx
  yarn.lock
Labels: bug, documentation, feature, improvement

#112 Unset filters after tests
  src/components/molecules/__tests__/Filters.test.tsx
Labels: bug

#114 Missing : in TabLabel.tsx
  src/components/atoms/TabLabel.tsx
Labels: bug

#108 Import types by using the import(...) function
  src/App.tsx
  src/components/atoms/AccentedLink.tsx
  src/components/atoms/BalanceTableEntry.tsx
  src/components/atoms/BalancesCalendarEntry.tsx
  src/components/atoms/Checkbox.tsx
  src/components/atoms/Collapsable.tsx
  src/components/atoms/Input.tsx
  src/components/atoms/MonthPicker.tsx
  src/components/atoms/NavigationBrand.tsx
  src/components/atoms/NavigationPill.tsx
  src/components/atoms/OutlinedButton.tsx
  src/components/atoms/PageTitle.tsx
  src/components/atoms/RecurringTransactionOptions.tsx
  src/components/atoms/Routes.tsx
  src/components/atoms/TabLabel.tsx
  src/components/atoms/TextArea.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/BalancesViewPicker.test.tsx
  src/components/atoms/__tests__/MonthPicker.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/BalancesCalendar.tsx
  src/components/molecules/BalancesTable.tsx
  src/components/molecules/DashboardTransactions.tsx
  src/components/molecules/ExpenseTransactions.tsx
  src/components/molecules/Filters.tsx
  src/components/molecules/IncomeTransactions.tsx
  src/components/molecules/TransactionCalculator.tsx
  src/components/organism/Navigation.tsx
  src/components/organism/Toolbar.tsx
  src/components/organism/Transactions.tsx
  src/components/organism/authentication/Login.tsx
  src/components/organism/authentication/Register.tsx
  src/components/pages/Balances.tsx
  src/components/pages/Companies.tsx
  src/components/pages/Homepage.tsx
  src/declarations/user.ts
  src/helpers/intermediary_calc.ts
  src/helpers/transaction_creator.tsx
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/company.ts
  src/mitochondria/transactions.ts
  src/store/reducers/auth.ts
  src/store/reducers/company.ts
  src/store/reducers/transactions.ts
Labels: improvement

#113 Use queryString and objects for query parameters
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/mitochondria/recurring.ts
  src/mitochondria/transactions.ts
Labels: improvement

#109 Filters now read query params initially
  package.json
  src/components/molecules/Filters.tsx
  src/mitochondria/auth.ts
  src/mitochondria/balances.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/mitochondria/recurring.ts
  src/mitochondria/transactions.ts
  yarn.lock
Labels: feature

#116 Fix broken interfaces after merge
  src/components/atoms/TransactionEntry.tsx
  src/components/molecules/Filters.tsx
  src/components/molecules/Tab.tsx
  src/components/molecules/TabsContainer.tsx
  src/components/pages/Dashboard.tsx
Labels: bug

#105 Feature/reducers
  src/__tests__/App.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/mitochondria/company.ts
  src/store/reducers/__tests__/auth.test.ts
  src/store/reducers/__tests__/company.test.ts
  src/store/reducers/__tests__/transactions.test.ts
  src/store/reducers/auth.ts
  src/store/reducers/company.ts
  src/store/reducers/transactions.ts
Labels: feature, testing

#120 Forgot to import ICompanyUser
  src/store/reducers/company.ts
Labels: bug
