Repository Kodeworks/liquidator, pull requests merged in 2019-08, with the labels that each got.

#122 Create and switch companies
  .circleci/config.yml
  .gitignore
  src/components/atoms/Routes.tsx
  src/components/atoms/Select.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/Filters.tsx
  src/components/organism/Navigation.tsx
  src/components/pages/Balances.tsx
  src/components/pages/CreateCompany.tsx
  src/helpers/test-utils.ts
  src/mitochondria/__test__/balances.ts
  src/mitochondria/__test__/transaction.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/store/contexts/company.tsx
  src/store/contexts/transactions.tsx
  src/store/reducers/auth.ts
  src/store/reducers/company.ts
  src/store/reducers/transactions.ts
Labels: feature, improvement, priority

#115 Feature/update and delete transactions
  .circleci/config.yml
  .gitignore
  src/App.tsx
  src/components/atoms/Routes.tsx
  src/components/atoms/Select.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/TransactionEntry.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/EditTransaction.tsx
  src/components/molecules/Filters.tsx
  src/components/organism/Navigation.tsx
  src/components/pages/Balances.tsx
  src/components/pages/CreateCompany.tsx
  src/helpers/test-utils.ts
  src/mitochondria/__test__/balances.ts
  src/mitochondria/__test__/transaction.ts
  src/mitochondria/company.ts
  src/mitochondria/index.ts
  src/store/contexts/company.tsx
  src/store/contexts/transactions.tsx
  src/store/reducers/auth.ts
  src/store/reducers/company.ts
  src/store/reducers/transactions.ts
Labels: feature

#125 Style radio buttons in AddTransaction.tsx
  src/components/atoms/RadioButton.tsx
  src/components/molecules/AddTransaction.tsx
Labels: improvement

#126 Feature/recurring
  src/components/atoms/RecurringTransactionOptions.tsx
  src/components/atoms/TransactionEntry.tsx
  src/components/atoms/__tests__/TransactionEntry.test.tsx
  src/components/molecules/AddTransaction.tsx
  src/components/molecules/EditTransaction.tsx
  src/components/molecules/ExpenseTransactions.tsx
  src/components/molecules/IncomeTransactions.tsx
  src/components/molecules/OverrideRecurringForm.tsx
  src/components/organism/Transactions.tsx
  src/declarations/transaction.ts
  src/helpers/flatMap.ts
  src/helpers/test-utils.ts
  src/mitochondria/__test__/transaction.ts
  src/store/contexts/transactions.tsx
  src/store/reducers/__tests__/transactions.test.ts
  src/store/reducers/transactions.ts
  src/stories/index.stories.tsx
Labels: feature, priority

#127 Added z-index 999 to the toolbar so that nothing shows infront of it
  src/components/organism/Toolbar.tsx
Labels: bug, good first issue, help wanted

#150 Implement pagination
  frontend/src/components/molecules/ExpenseTransactions.tsx
  frontend/src/components/molecules/IncomeTransactions.tsx
  frontend/src/components/organism/Transactions.tsx
  frontend/src/helpers/pagination_iterator.ts
  frontend/src/mitochondria/__test__/balances.ts
  frontend/src/mitochondria/__test__/transaction.ts
  frontend/src/mitochondria/balances.ts
  frontend/src/mitochondria/recurring.ts
  frontend/src/mitochondria/transactions.ts
  frontend/src/store/contexts/transactions.tsx
  frontend/src/store/reducers/transactions.ts
Labels: improvement, priority
